const ClassroomActionTypes = {
  FETCH_CLASSROOMS_REQUEST: "FETCH_CLASSROOMS_REQUEST",
  FETCH_CLASSROOMS_SUCCESS: "FETCH_CLASSROOMS_SUCCESS",
  FETCH_CLASSROOMS_FAILURE: "FETCH_CLASSROOMS_FAILURE",
  CREATE_A_CLASSROOM_REQUEST: "CREATE_A_CLASSROOM_REQUEST",
  CREATE_A_CLASSROOM_SUCCESS: "CREATE_A_CLASSROOM_SUCCESS",
  CREATE_A_CLASSROOM_FAILURE: "CREATE_A_CLASSROOM_FAILURE",
  CLEAR_CLASSROOMS: "CLEAR_CLASSROOMS",
  FETCH_A_CLASSROOM_REQUEST: "FETCH_A_CLASSROOM_REQUEST",
  FETCH_A_CLASSROOM_SUCCESS: "FETCH_A_CLASSROOM_SUCCESS",
  FETCH_A_CLASSROOM_FAILURE: "FETCH_A_CLASSROOM_FAILURE",
  CLOSE_CLASSROOM: "CLOSE_CLASSROOM",
};

export default ClassroomActionTypes;
