const ClassroomActionTypes = {
  FETCH_A_CLASSROOM_REQUEST: "FETCH_A_CLASSROOM_REQUEST",
  FETCH_A_CLASSROOM_SUCCESS: "FETCH_A_CLASSROOM_SUCCESS",
  FETCH_A_CLASSROOM_FAILURE: "FETCH_A_CLASSROOM_FAILURE",
  CLOSE_CLASSROOM: "CLOSE_CLASSROOM",
  CREATE_A_CLASSROOM_REQUEST: "CREATE_A_CLASSROOM_REQUEST",
  CREATE_A_CLASSROOM_SUCCESS: "CREATE_A_CLASSROOM_SUCCESS",
  CREATE_A_CLASSROOM_FAILURE: "CREATE_A_CLASSROOM_FAILURE",
  UPDATE_CLASSROOM_REQUEST: "UPDATE_CLASSROOM_REQUEST",
  UPDATE_CLASSROOM_SUCCESS: "UPDATE_CLASSROOM_SUCCESS",
  UPDATE_CLASSROOM_FAILURE: "UPDATE_CLASSROOM_FAILURE",
  UPLOAD_STUDENT_LIST_REQUEST: "UPLOAD_STUDENT_LIST_REQUEST",
  UPLOAD_STUDENT_LIST_SUCCESS: "UPLOAD_STUDENT_LIST_SUCCESS",
  UPLOAD_STUDENT_LIST_FAILURE: "UPLOAD_STUDENT_LIST_FAILURE",
};

export default ClassroomActionTypes;
