const ClassroomActionTypes = {
  FETCH_CLASSROOMS_REQUEST: "FETCH_CLASSROOMS_REQUEST",
  FETCH_CLASSROOMS_SUCCESS: "FETCH_CLASSROOMS_SUCCESS",
  FETCH_CLASSROOMS_FAILURE: "FETCH_CLASSROOMS_FAILURE",
  CREATE_A_CLASSROOM_REQUEST: "CREATE_A_CLASSROOM_REQUEST",
  CREATE_A_CLASSROOM_SUCCESS: "CREATE_A_CLASSROOM_SUCCESS",
  CREATE_A_CLASSROOM_FAILURE: "CREATE_A_CLASSROOM_FAILURE",
};

export default ClassroomActionTypes;
