const UserActionTypes = {
  EMAIL_LOGIN_REQUEST: "EMAIL_LOGIN_REQUEST",
  EMAIL_LOGIN_SUCCESS: "EMAIL_LOGIN_SUCCESS",
  EMAIL_LOGIN_FAILURE: "EMAIL_LOGIN_FAILURE",
  FACEBOOK_LOGIN: "FACEBOOOK_LOGIN",
  GOOGLE_LOGIN: "GOOGLE_LOGIN",
  LOGOUT: "LOGOUT",
};

export default UserActionTypes;
