const UserActionTypes = {
  EMAIL_LOGIN_REQUEST: "EMAIL_LOGIN_REQUEST",
  EMAIL_LOGIN_SUCCESS: "EMAIL_LOGIN_SUCCESS",
  EMAIL_LOGIN_FAILURE: "EMAIL_LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  FETCH_A_USER_REQUEST: "FETCH_A_USER_REQUEST",
  FETCH_A_USER_SUCCESS: "FETCH_A_USER_SUCCESS",
  FETCH_A_USER_FAILURE: "FETCH_A_USER_FAILURE",
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
};

export default UserActionTypes;
