const UserActionTypes = {
  EMAIL_LOGIN_REQUEST: "EMAIL_LOGIN_REQUEST",
  EMAIL_LOGIN_SUCCESS: "EMAIL_LOGIN_SUCCESS",
  EMAIL_LOGIN_FAILURE: "EMAIL_LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
};

export default UserActionTypes;
